### ISSUE TITLE
cleaning function

### ISSUE THREAD

**Issue by hadrilec** [dataforgoodfr/batch9_geowatchlabs-3-markets#4]
Mettre des underscores à la place des espaces dans le nom des colonnes, pour intégrer toutes les colonnes dans le dataset final.
@MonsieurCroque j'ai du mal à m'y retrouver dans les fonctions d'agrégation et de nettoyage, est ce que tu vois comment faire?

**Comment by MonsieurCroque** [comment]
Fait !
